### ISSUE TITLE
SQL error - no such table: metadata

### ISSUE THREAD

**Issue by Prognda** [Apr4h/HarvestBrowserPasswords#1]
Trying to fetch data from key4.db.

FF version:76.0 (64bit)
Windows: Windows 7 Home Premium 64bit
key4.db path: C:\Users****\AppData\Roaming\Mozilla\Firefox\Profiles\109dfhpb.default-release
Error message: https://imgur.com/38m1ynj

**Comment by Apr4h** [comment]
Thanks for raising this issue. Looking into this made me realise that as of Firefox Version 75.0, key4.db and logins.json now use sha1 pbkdf2 sha256 aes256 cbc. As such, this tool will currently only be able to decrypt stored logins for Firefox versions 58.0.2 through 74.

If I get time I will look at adding support for future versions of Firefox.

**Comment by Apr4h** [comment]
For now I've updated the program to catch the unhandled exception when it cannot correctly parse the contents of key4.db and prompt the user that the Firefox version may be incorrect. 8bfeb10727ccb7f6132a304d5d84bfd913257a28

**Comment by Prognda** [comment]
Hi, 
Any updates?

**Comment by Apr4h** [comment]
Hi, sorry for the delay. I probably won't be adding support for more recent versions of Firefox in the near future. Please feel to have a look at the code and submit a pull request if you'd like to try it yourself.
